### ISSUE TITLE
FYC: For Your Curiosity :)

### ISSUE THREAD

**Issue by mindey** [kmturley/decimal-time#10]
I'm using the decimal time in our community site - https://0oo.li .
The calendar looks a bit like this: https://0oo.li/calendar/ .

Organizing work in 10-day ("dweekly") sprints feels somehow more natural than in weeks:

More substantial work can be done in 10 days, which is probably a reason why companies often have sprints longer than 1 week, but shorter than 2 weeks. 10-days appears to be smack in the middle of that (floor((7+14)/2) = 10) indecision. :)

**Comment by kmturley** [comment]
Very interesting. Would be cool to have a project management tool based on decimal time!

It's a lot of work though!
